# Generated by Django 5.1.1 on 2025-08-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asteroid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neo_reference_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('nasa_jpl_url', models.URLField()),
                ('absolute_magnitude_h', models.FloatField()),
                ('estimated_diameter_min', models.FloatField(help_text='Estimated diameter in kilometers (min)')),
                ('estimated_diameter_max', models.FloatField(help_text='Estimated diameter in kilometers (max)')),
                ('is_potentially_hazardous', models.BooleanField(default=False)),
                ('is_sentry_object', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Near-Earth Asteroid',
                'verbose_name_plural': 'Near-Earth Asteroids',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloseApproach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_approach_date', models.DateTimeField()),
                ('relative_velocity_km_per_sec', models.FloatField()),
                ('relative_velocity_km_per_hour', models.FloatField()),
                ('miss_distance_astronomical', models.FloatField()),
                ('miss_distance_lunar', models.FloatField()),
                ('miss_distance_kilometers', models.FloatField()),
                ('orbiting_body', models.CharField(default='Earth', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asteroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_approaches', to='asteroids.asteroid')),
            ],
            options={
                'verbose_name': 'Close Approach',
                'verbose_name_plural': 'Close Approaches',
                'ordering': ['close_approach_date'],
                'unique_together': {('asteroid', 'close_approach_date')},
            },
        ),
    ]
