# Generated by Django 5.1.1 on 2025-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('explanation', models.TextField()),
                ('url', models.URLField()),
                ('media_type', models.CharField(max_length=20)),
                ('hdurl', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Astronomy Picture of the Day',
                'verbose_name_plural': 'Astronomy Pictures of the Day',
                'ordering': ['-date'],
            },
        ),
    ]
