# Generated by Django 5.1.1 on 2025-08-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarFlare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flare_id', models.CharField(max_length=100, unique=True)),
                ('flare_class', models.CharField(choices=[('A', 'A-Class'), ('B', 'B-Class'), ('C', 'C-Class'), ('M', 'M-Class'), ('X', 'X-Class')], max_length=1)),
                ('begin_time', models.DateTimeField()),
                ('peak_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('source_location', models.CharField(blank=True, max_length=200)),
                ('active_region_num', models.CharField(blank=True, max_length=50)),
                ('linked_events', models.JSONField(blank=True, default=list)),
                ('instruments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solar Flare',
                'verbose_name_plural': 'Solar Flares',
                'ordering': ['-peak_time'],
            },
        ),
    ]
